# Cursor style
[cursor.style]
shape = "Beam"

[shell]
program = "/bin/fish"

# Font settings
[font]
size = 11

# [font.normal]
# family = "FontAwesome4"
# style = "Regular"
# 
# [font.bold]
# family = "FontAwesome4"
# style = "Bold"
# 
# [font.italic]
# family = "FontAwesome4"
# style = "Italic"

# Window settings
[window]
opacity = 0.9

[window.padding]
x = 15
y = 15

# theme
# import = ["~/.config/alacritty/themes/catppuccin_mocha.toml"]
